# Generated by Django 3.1.2 on 2020-10-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(default=None, max_length=200)),
                ('description', models.CharField(default=None, max_length=200)),
                ('director', models.CharField(default=None, max_length=200)),
                ('producer', models.CharField(default=None, max_length=200)),
                ('release_date', models.CharField(default=None, max_length=200)),
                ('rt_score', models.CharField(default=None, max_length=200)),
                ('people', models.CharField(default=None, max_length=200)),
                ('species', models.CharField(default=None, max_length=200)),
                ('locations', models.CharField(default=None, max_length=200)),
                ('vehicles', models.CharField(default=None, max_length=200)),
                ('url', models.CharField(default=None, max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Peoples',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(blank=True, max_length=200)),
                ('age', models.CharField(blank=True, max_length=200)),
                ('eye_color', models.CharField(blank=True, max_length=200)),
                ('hair_color', models.CharField(blank=True, max_length=200)),
                ('species', models.CharField(blank=True, max_length=200)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('films', models.ManyToManyField(blank=True, related_name='peoples', to='ghibli.Films')),
            ],
        ),
    ]
