# Generated by Django 3.1.2 on 2020-10-16 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghibli', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='people',
        ),
    ]
